### ISSUE TITLE
Trouble when using regions in the front-end

### ISSUE THREAD

**Issue by gaetzone** [bleutzinn/grav-plugin-editable#10] opened 2017-05-23 00:18 UTC
Hi everyone,
I got these issues when I'm using Editable Plugin in the front-end whether using ContentTools or Simplemde.

#Issue 1 :
I put this shortcode : [editable name="part1" /]  in the markdown file called foo.md
I've create a part1.md file in a sub directory with some text.
I could edit and modify the part1.md file but when I'm saving change, the whole content of the foo.md file is override by the content of part1.md.

#Issue 2 :
As I would like to put the file to include in the same directory than the father file, I'm writing this shortcode : [editable name="part1" /foo], but it doesn't work.
The shortcode is not interpreted.

Does anyone got already these issues ?

Thanks in advance for your help.
Best regards

**Comment by bleutzinn** [comment] 2017-05-23 06:48
Issue 1 is because you are probably using the shortcode in a page on with "editable_self: true". Set editable_self to false in the plugin config file or in the page header/frontmatter of foo. 

Issue 2 is caused by an invalid shortcode. The file to include is a Grav page. So it has it's own directory (or folder). If you want part1 to be inside foo you can do so by making part1 a child page of foo. Then use a relative path in the shortcode. See your shortcode from issue 1.

**Comment by gaetzone** [comment] 2017-05-23 07:32
Hi Bleutzinn.
Thanks for your reply but I guess the trouble is coming from somewhere else.
Please find code and commentaries below :

File foo.md :
> ---
> slug: foo
> editable:
>     enabled: true
>     editor: simplemde
>     editable_self: false
> shortcode-core:
>     active: true
> ---
> # Title1
> Lorem ipsum
> [editable name="part1" /]   ==> inclusion of /part1/part1.md content is working but saving override the whole content of foo.md. I would like to override only the content of part1.md
> [editable name="part2" /]   ==> inclusion of /part2/part2.md content is not working. Nothing is displayed.
> [editable name="part3" /part3] ==> inclusion of /part3.md content is not working. The shortcode is not interpretated. [editable name="part3" /part3] is outputed.
> ## Tittle2

**Comment by bleutzinn** [comment] 2017-05-23 08:20
You have added the complete plugin config to the page frontmatter. Inserting:
```
editable:
    editable_self: true
```
is sufficient. I'm not sure whether the extra variables are causing trouble. Sure thing is that you can not set the editor to use in the page.

Another point is that the SimpleMDE add-on does not support editable regions. When using SimpleMDE shortcodes are simply ignored. Your shortcodes do get processed which means that you have the ContentTools add-on active as well. The two add-ons can't both be enabled.

If you want to use editable regions please remove the SimpleMDE add-on and check your config in `user/config/plugins/editable.yaml` and in your page frontmatter to make sure there are no references to SimpleMDE.
Also make sure your page content is HTML as ContentTools can not work with markdown. I've added some extra notes on that in the ReadMe document.

**Comment by gaetzone** [comment] 2017-05-24 09:04
Thanks for your reply Bleutzinn but I'm a little bit confusing.

- Whether I define the editable_self variable in the page or in the user/config/plugins/editable.yaml, the result is the same.

- I cannot set the editable_self variable to true because I want to use ediable regions. So I have to write short code  [editable name="xxx" /] in places I want to be editable

- I cannot use only html as I want to use editable region. So I have to write some short code.

- When using contenttools instead of simplemde, I can edit each regions of the page but saving is not working. After saving I got the green check icon but I still get the original content. I guess the script that would override the edited md file is missing.

**Comment by bleutzinn** [comment] 2017-05-27 08:27
Please see my answer after each subject:

> Whether I define the editable_self variable in the page or in the user/config/plugins/editable.yaml, the result is the same.

The difference is that the variable in user/config/plugins/editable.yaml is a site wide setting (so for all pages) and the variable in the page frontmatter works in that page only. This allows you to disable Editable Self mode site wide and enable it for some pages.

> I cannot set the editable_self variable to true because I want to use ediable regions. So I have to write short code [editable name="xxx" /] in places I want to be editable

Yes. Both Editable modes can not be used at the same time.

> I cannot use only html as I want to use editable region. So I have to write some short code.

The page with the shortcode(s) can be HTML. However, the shortcodes should not be inside HTML elements. For example:
this is good:
```
<p>Before shortcode.</p>
[editable name="part1" /]
<p>After shortcode.</p>
```
this is **not** good:
```
<p>Before shortcode.
[editable name="part1" /]
After shortcode.</p>
```

> When using contenttools instead of simplemde, I can edit each regions of the page but saving is not working. After saving I got the green check icon but I still get the original content. I guess the script that would override the edited md file is missing.

This could be caused by having caching enabled. Unfortunately the current release of Editable only works with caching disabled.

**Comment by bleutzinn** [comment] 2017-07-03 19:12
I'm closing this issue as I discontinue the development and support of this plugin.

**Closed by bleutzinn** 2017-07-03 19:12 UTC
Labels: question
